stages:
  - deploy

deploy-to-k3s:
  stage: deploy
  tags:
    - k3s  # This tells GitLab to use local server!
  script:
    - echo "Deploying to the local Lab..."
    - /usr/local/bin/kubectl apply -f deployment.yaml
    - /usr/local/bin/kubectl get pods